apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-r6
spec:
  replicas: 1
  selector:
    matchLabels:
        app: ml-r6-app
  template:
    metadata:
      labels:
        app: ml-r6-app
    spec:
      volumes:
      - configMap:
          defaultMode: 0755
          name: ml-config
        name: ml-config
      containers:
      - name: ml-r6-service
        image: mariovicente/ml:latest
        command: ["python3", "-u", "/ml/ml.py"]
        args: ["TP_r6", "ML_r6"]
        volumeMounts:
        - name: ml-config
          mountPath: /ml/ml-config.txt
          subPath: ml-config.txt
        
      
        
        