apiVersion: apps/v1
kind: Deployment
metadata:
  name: r1
spec:
  replicas: 1
  selector:
    matchLabels:
        app: r1-app
  template:
    metadata:
      labels:
        app: r1-app
    spec:
      containers:
      - name: r1-service
        image: mariovicente/router-node-exporter:latest
        ports:
        - containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: r1-service
  labels:
    name: r1-app
spec:
  ports:
  - name: r1-port
    port: 9100
    protocol: TCP
  selector:
    app: r1-app
