apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: kafka-broker
  name: kafka-broker
spec:
  selector:
    matchLabels:
      service: kafka-broker
  serviceName: "kafka-service"
  replicas: 1
  template:
    metadata:
      labels:
        service: kafka-broker
    spec:
      containers:
      - env:
        - name: MY_HOST_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_ADVERTISED_LISTENERS
          #value: INTERNAL://$(MY_POD_NAME).kafka-service.across-tc32.svc.cluster.local:9092,EXTERNAL://138.4.21.11:30092
          value: INTERNAL://$(MY_POD_NAME).kafka-service.across-tc32.svc.cluster.local:9092,EXTERNAL://138.4.21.11:30092
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
        - name: KAFKA_LISTENERS
          #value: INTERNAL://:9092,EXTERNAL://:30092
          value: INTERNAL://:9092,EXTERNAL://:30092
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
        - name: KAFKA_PORT
          value: "9092"
        #- name: KAFKA_RESTART_ATTEMPTS
        #  value: "10"
        #- name: KAFKA_RESTART_DELAY
        #  value: "5"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
        - name: JAVA_OPTS
          value: "-Xms256m -Xmx256m"
        #- name: KAFKA_ZOOKEEPER_SESSION_TIMEOUT
        #  value: "6000"
        #- name: ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL
        #  value: "0"
        #- name: KAFKA_ADVERTISED_PORT
        #  value: "9092"
        #- name: KAFKA_ADVERTISED_HOST_NAME
        #  value: kafka-service
        #- name: KAFKA_LOG_DIRS
        #  value: "/tmp/kafka-logs"
        #- name: KAFKA_BROKER_ID
        #  value: "0"
        #- name: KAFKA_ADVERTISED_HOST_NAME
        #  value: $(POD_IP)
        image: wurstmeister/kafka
        name: kafka-broker
        ports:
        - containerPort: 9092
 
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: kafka-service
  name: kafka-service
spec:
  type: NodePort
  ports:
  - name: kafka-port
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: kafka-advertised-port
    port: 30092
    protocol: TCP
    targetPort: 30092
    nodePort: 30092
  selector:
    service: kafka-broker